"use client"

import { Card } from "@/components/ui/card"
import { motion, AnimatePresence } from "framer-motion"
import { Play, X } from "lucide-react"
import { useState } from "react"

const videos = [
    {
        id: 1,
        title: "Luxury Real Estate",
        category: "Property",
        videoUrl: "https://cdn.coverr.co/videos/coverr-modern-apartment-interior-8557/1080p.mp4"
    },
    {
        id: 2,
        title: "Tech Product Launch",
        category: "SaaS",
        videoUrl: "https://cdn.coverr.co/videos/coverr-typing-on-laptop-2633/1080p.mp4"
    },
    {
        id: 3,
        title: "Gourmet Experience",
        category: "F&B",
        videoUrl: "https://cdn.coverr.co/videos/coverr-pouring-coffee-into-a-cup-2617/1080p.mp4"
    },
    {
        id: 4,
        title: "Engineering Solutions",
        category: "Industry",
        videoUrl: "https://cdn.coverr.co/videos/coverr-welding-metal-part-2735/1080p.mp4"
    },
    {
        id: 5,
        title: "Personal Brand Story",
        category: "Creator",
        videoUrl: "https://cdn.coverr.co/videos/coverr-a-woman-filming-herself-with-a-smartphone-5231/1080p.mp4"
    },
    {
        id: 6,
        title: "Daily Adventure",
        category: "Vlog",
        videoUrl: "https://cdn.coverr.co/videos/coverr-walking-through-a-forest-8575/1080p.mp4"
    },
]

export default function Showcase() {
    const [playingId, setPlayingId] = useState<number | null>(null)

    return (
        <section id="showcase" className="py-32 px-6 bg-secondary/5">
            <div className="max-w-6xl mx-auto space-y-16">
                <div className="text-center space-y-4">
                    <h2 className="text-4xl md:text-5xl font-bold tracking-tight">Built with Beyond</h2>
                    <p className="text-muted-foreground text-lg max-w-xl mx-auto">
                        Experience the quality of videos generated by Beyond Social Media Marketing. Click to play.
                    </p>
                </div>

                <div className="grid grid-cols-2 md:grid-cols-3 gap-8">
                    {videos.map((video, i) => (
                        <motion.div
                            key={video.id}
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            transition={{ delay: i * 0.1 }}
                            viewport={{ once: true }}
                        >
                            <Card
                                onClick={() => setPlayingId(video.id)}
                                className="border-border/40 overflow-hidden group cursor-pointer relative bg-background shadow-xl hover:shadow-primary/5 transition-all duration-500 -py-4"
                            >
                                <div className="aspect-9/16 bg-muted relative">
                                    <AnimatePresence mode="wait">
                                        {playingId === video.id ? (
                                            <motion.div
                                                key="video"
                                                initial={{ opacity: 0 }}
                                                animate={{ opacity: 1 }}
                                                exit={{ opacity: 0 }}
                                                className="absolute inset-0 z-20"
                                            >
                                                <video
                                                    src={video.videoUrl}
                                                    autoPlay
                                                    controls
                                                    className="w-full h-full object-cover"
                                                    onEnded={() => setPlayingId(null)}
                                                />
                                                <button
                                                    onClick={(e) => {
                                                        e.stopPropagation()
                                                        setPlayingId(null)
                                                    }}
                                                    className="absolute top-4 right-4 z-30 size-10 rounded-full bg-black/50 backdrop-blur-md flex items-center justify-center text-white hover:bg-black/70 transition-colors"
                                                >
                                                    <X className="size-5" />
                                                </button>
                                            </motion.div>
                                        ) : (
                                            <motion.div
                                                key="thumbnail"
                                                initial={{ opacity: 0 }}
                                                animate={{ opacity: 1 }}
                                                exit={{ opacity: 0 }}
                                                className="absolute inset-0"
                                            >
                                                <div className="absolute inset-0 bg-linear-to-t from-black/80 via-black/20 to-transparent z-10" />

                                                {/* Category & Title */}
                                                <div className="absolute bottom-6 left-6 right-6 z-10 transition-transform duration-500 group-hover:translate-y-[-8px]">
                                                    <p className="text-xs font-bold text-primary mb-2 uppercase tracking-[0.2em]">{video.category}</p>
                                                    <p className="text-xl font-bold text-white leading-tight">{video.title}</p>
                                                </div>

                                                {/* Play Button Overlay */}
                                                <div className="absolute inset-0 flex items-center justify-center z-10 group-hover:bg-primary/5 transition-colors duration-500">
                                                    <div className="size-16 rounded-full bg-white/10 backdrop-blur-md group-hover:bg-primary group-hover:scale-110 flex items-center justify-center border border-white/20 group-hover:border-primary transition-all duration-500 shadow-2xl">
                                                        <Play className="size-6 text-white fill-white ml-1 group-hover:scale-110 transition-transform" />
                                                    </div>
                                                </div>

                                                {/* Static Background Image (using a placeholder or color gradient) */}
                                                <div className="w-full h-full bg-linear-to-br from-secondary via-background to-secondary/40" />
                                            </motion.div>
                                        )}
                                    </AnimatePresence>
                                </div>
                            </Card>
                        </motion.div>
                    ))}
                </div>
            </div>
        </section>
    )
}
